version: "2"
services:
  bot_telegram:
    container_name: bot_telegram
    build: .
    networks:
      - webhook
    volumes:
      - ./cron/cron_main:/etc/crontabs_bot/root

networks:
    webhook:
      external:
        name: trae
